version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: doc_management
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ~/middleware/postgres/data
        target: /var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 12345678
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - type: bind
        source: ~/middleware/minio/data
        target: /data
    restart: unless-stopped

  backend:
    image: ghcr.io/simongino/file-manager-backend:main
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - minio
    restart: unless-stopped

  frontend:
    image: ghcr.io/simongino/file-manager-frontend:main
    container_name: frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: